"""M1 accounting control roles and categories."""
from __future__ import annotations

CONTROL_AR = "AR"
CONTROL_AP = "AP"
CONTROL_INVENTORY = "INVENTORY"
CONTROL_CASH = "CASH"
CONTROL_VAT_INPUT = "VAT_INPUT"
CONTROL_VAT_OUTPUT = "VAT_OUTPUT"
CONTROL_REVENUE = "REVENUE"
CONTROL_COGS = "COGS"
CONTROL_EXPENSE = "EXPENSE"
CONTROL_INVENTORY_SHRINKAGE = "INVENTORY_SHRINKAGE"
CONTROL_RETAINED_EARNINGS = "RETAINED_EARNINGS"

DEFAULT_COA_TEMPLATE = (
    ("1100", "Accounts Receivable", "ASSET", CONTROL_AR, "DEBIT"),
    ("1200", "Inventory", "ASSET", CONTROL_INVENTORY, "DEBIT"),
    ("1300", "VAT Input", "ASSET", CONTROL_VAT_INPUT, "DEBIT"),
    ("1400", "Cash and Bank", "ASSET", CONTROL_CASH, "DEBIT"),
    ("2100", "Accounts Payable", "LIABILITY", CONTROL_AP, "CREDIT"),
    ("2200", "VAT Output", "LIABILITY", CONTROL_VAT_OUTPUT, "CREDIT"),
    ("3000", "Retained Earnings", "EQUITY", CONTROL_RETAINED_EARNINGS, "CREDIT"),
    ("4000", "Sales Revenue", "REVENUE", CONTROL_REVENUE, "CREDIT"),
    ("5000", "Cost of Sales", "COGS", CONTROL_COGS, "DEBIT"),
    ("6000", "Operating Expenses", "EXPENSE", CONTROL_EXPENSE, "DEBIT"),
    ("6100", "Inventory Shrinkage & Adjustments", "EXPENSE", CONTROL_INVENTORY_SHRINKAGE, "DEBIT"),
)

BALANCE_TOLERANCE = "0.01"
